### ISSUE TITLE
Cannot read property 'setEnvironment' of null

### ISSUE THREAD

**Issue by Navakanth-Nava** [DeepPatel-21/react-native-aauti-pay#1]
Iam getting this issue from the path nodemodules\react-native-aauti-pay\components\CardDetail\index.js
![Screenshot_2023-09-27-17-09-22-48_200dd2c0af12ea1e71d93ea76f51950d](https://github.com/DeepPatel-21/react-native-aauti-pay/assets/85012137/bb9b900e-33b9-49bf-95a2-e09657af2e5f)

**Comment by deep-groovy** [comment]
I think you have issue in linking react-native-google-pay. Please try
manuall linking from https://www.npmjs.com/package/react-native-google-pay
here & let me know it'sfix for you or not.
